import type { Metadata } from "next";
import "./globals.css";
import { AppHeader } from "@/components/Header";
import { AppFooter } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Pet Adoption Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='font-Sans bg-[#ebe3cc]'>
        <AppHeader />
        {children}
        <AppFooter />
      </body>
    </html>
  );
}
